# Generated by Django 4.2.24 on 2026-08-05 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_project_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certification', '0030_certifyingorganisation_vat_number_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.attendee'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.course'),
        ),
        migrations.AlterField(
            model_name='certifyingorganisation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.project'),
        ),
        migrations.AlterField(
            model_name='certifyingorganisationcertificate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certifyingorganisationcertificate',
            name='certifying_organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.certifyingorganisation'),
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='certifying_organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.certifyingorganisation'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_convener',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.courseconvener'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.coursetype'),
        ),
        migrations.AlterField(
            model_name='course',
            name='training_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.trainingcenter'),
        ),
        migrations.AlterField(
            model_name='courseattendee',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.attendee'),
        ),
        migrations.AlterField(
            model_name='courseattendee',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courseattendee',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.course'),
        ),
        migrations.AlterField(
            model_name='courseconvener',
            name='certifying_organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.certifyingorganisation'),
        ),
        migrations.AlterField(
            model_name='courseconvener',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='certifying_organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.certifyingorganisation'),
        ),
        migrations.AlterField(
            model_name='trainingcenter',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingcenter',
            name='certifying_organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.certifyingorganisation'),
        ),
    ]
