#
# Production server with UWSGI configured to run on port 8080
# and web configured to run directly on port 80
#
# docker-compose build
# docker-compose up -d web
#
# See accompanying Make commands for easy collectstatic etc.
volumes:
  postgres-data:
  db-backups:
  static-data:
  media-data:
  reports-data:
  nginx-conf:
services:
  smtp:
    image: catatnight/postfix
    hostname: postfix
    environment:
      # You could change this to something more suitable
      - maildomain=kartoza.com
      - smtp_user=noreply:docker
    restart: unless-stopped

  db:
    image: kartoza/postgis:16-3.4
    volumes:
      - postgres-data:/var/lib/postgresql
      - db-backups:/backups
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASS=${DATABASE_PASSWORD}
      - ALLOW_IP_RANGE=0.0.0.0/0
    restart: unless-stopped
    ports:
      - "7543:5432"

  uwsgi: &uwsgi-common
    build:
      context: ${PWD}/../
      dockerfile: deployment/docker/Dockerfile
      target: prod
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
    volumes:
      - static-data:/home/web/static:rw
      - media-data:/home/web/media:rw
      - reports-data:/home/web/reports
    links:
      - db:db
    restart: unless-stopped
    user: root
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  dbbackups:
    image: kartoza/pg-backup:16-3.4
    hostname: pg-backups
    volumes:
      - db-backups:/backups
    links:
      - db:db
    environment:
      # take care to let the project name below match that
      # declared in the top of the makefile
      - DUMPPREFIX=${DUMPPREFIX}
      # These are all defaults anyway, but setting explicitly in
      # case we ever want to ever use different credentials
      - PGUSER=${DATABASE_USERNAME}
      - PGPASSWORD=${DATABASE_PASSWORD}
      - PGPORT=5432
      - PGHOST=${DATABASE_HOST}
      - PGDATABASE=${DATABASE_NAME}
    restart: unless-stopped

  # This is normally the main entry point for a production server
  web:
    image: nginx
    volumes:
      - nginx-conf:/etc/nginx/conf.d:ro
      - static-data:/home/web/static:ro
      - media-data:/home/web/media:ro
    links:
      - uwsgi:uwsgi
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  # This is the entry point for a development server.
  # Run with --no-deps to run attached to the services
  # from prod environment if wanted
  devweb:
    <<: *uwsgi-common
    build:
      context: ${PWD}/../
      dockerfile: dockerize/docker/Dockerfile
      target: dev



